import {
  MatButtonModule,
  MatCheckboxModule,
  MatFormFieldModule,
  MatInputModule,
  MatSelectModule,
  MatProgressSpinnerModule,
  // MatGridListModule,
  MatListModule,
  MatStepperModule,
  MatRadioModule,
  MatButtonToggleModule,
  MatSlideToggleModule,
  MatExpansionModule,
  MatSnackBarModule,
  MatIconModule,
  MatMenuModule,
  MatDialogModule,
  MatTooltipModule
} from '@angular/material';
import { NgModule } from '@angular/core';

@NgModule({
  imports: [
    MatButtonModule,
    MatCheckboxModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatProgressSpinnerModule,
    // MatGridListModule,
    MatListModule,
    MatStepperModule,
    MatRadioModule,
    MatButtonToggleModule,
    MatSlideToggleModule,
    MatExpansionModule,
    MatSnackBarModule,
    MatIconModule,
    MatMenuModule,
    MatDialogModule,
    MatTooltipModule
  ],
  exports: [
    MatButtonModule,
    MatCheckboxModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatProgressSpinnerModule,
    // MatGridListModule,
    MatListModule,
    MatStepperModule,
    MatRadioModule,
    MatButtonToggleModule,
    MatSlideToggleModule,
    MatExpansionModule,
    MatSnackBarModule,
    MatIconModule,
    MatMenuModule,
    MatDialogModule,
    MatTooltipModule
  ],
})
export class MaterialModule { }
